<?php
/* @var $this SupplementarySalaryDetailsController */
/* @var $model SupplementarySalaryDetails */

$this->breadcrumbs=array(
	'Supplementary Salary Details'=>array('index'),
	$model->ID,
);

$this->menu=array(
	array('label'=>'List SupplementarySalaryDetails', 'url'=>array('index')),
	array('label'=>'Create SupplementarySalaryDetails', 'url'=>array('create')),
	array('label'=>'Update SupplementarySalaryDetails', 'url'=>array('update', 'id'=>$model->ID)),
	array('label'=>'Delete SupplementarySalaryDetails', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->ID),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage SupplementarySalaryDetails', 'url'=>array('admin')),
);
?>

<h1>View SupplementarySalaryDetails #<?php echo $model->ID; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'ID',
		'EMPLOYEE_ID_FK',
		'BASIC',
		'SP',
		'PP',
		'CCA',
		'HRA',
		'DA',
		'TA',
		'IT',
		'CGHS',
		'LF',
		'CGEGIS',
		'CPF_TIER_I',
		'CPF_TIER_II',
		'HBA_EMI',
		'MCA_EMI',
		'FAN_EMI',
		'FLOOD_EMI',
		'CYCLE_EMI',
		'PLI',
		'MISC',
		'PT',
		'FEST_EMI',
		'HBA_TOTAL',
		'MCA_TOTAL',
		'FLOOD_TOTAL',
		'CYCLE_TOTAL',
		'FEST_TOTAL',
		'HBA_INST',
		'MCA_INST',
		'FLOOD_INST',
		'CYCLE_INST',
		'FEST_INST',
		'HBA_BAL',
		'MCA_BAL',
		'FLOOD_BAL',
		'CYCLE_BAL',
		'FEST_BAL',
		'WA',
		'CCS',
		'LIC',
		'ASSOSC_SUB',
		'REMARKS',
		'FAN_TOTAL',
		'FAN_INST',
		'FAN_BAL',
		'MONTH',
		'YEAR',
		'GP',
		'GROSS',
		'DED',
		'NET',
		'OTHER_DED',
		'AMOUNT_BANK',
		'IS_SALARY_BILL',
		'IS_FEST_RECOVERY',
		'IS_HBA_RECOVERY',
		'IS_MCA_RECOVERY',
		'IS_FLOOD_RECOVERY',
		'IS_CYCLE_RECOVERY',
		'IS_FAN_RECOVERY',
		'MAINT_MADIWALA',
		'MAINT_JAYAMAHAL',
		'COURT_ATTACHMENT',
		'EL_ENCASHMENT',
	),
)); ?>
